#!/usr/bin/env python3
"""
UI Mockup Generator for RMinder First-Run Experience
Generates ASCII art representations of the key onboarding screens
"""

def print_onboarding_screen():
    print("=" * 60)
    print("           RMINDER ONBOARDING SCREEN")
    print("=" * 60)
    print()
    print("    ┌─────────────────────────────────────────────┐")
    print("    │                                             │")
    print("    │              [💳 ICON]                      │")
    print("    │                                             │")
    print("    │           Welcome to RMinder!               │")
    print("    │      Your privacy-first budgeting          │")
    print("    │             companion                       │")
    print("    │                                             │")
    print("    │    📊 Smart Budgeting                       │")
    print("    │    Plan and track expenses by category      │")
    print("    │                                             │")
    print("    │    💰 Debt Management                       │")
    print("    │    Track liabilities and plan payments     │")
    print("    │                                             │")
    print("    │    🎯 Savings Goals                         │")
    print("    │    Set and achieve savings targets          │")
    print("    │                                             │")
    print("    │    🔒 Privacy First                         │")
    print("    │    All data stays on your device           │")
    print("    │                                             │")
    print("    │    ┌─────────────────┐  ┌─────────────────┐ │")
    print("    │    │   Get Started   │  │   Learn More    │ │")
    print("    │    └─────────────────┘  └─────────────────┘ │")
    print("    │                                             │")
    print("    └─────────────────────────────────────────────┘")
    print()

def print_tips_screen():
    print("=" * 60)
    print("              RMINDER TIPS SCREEN")
    print("=" * 60)
    print()
    print("    ┌─────────────────────────────────────────────┐")
    print("    │  ← How to Use RMinder              [?]      │")
    print("    │     Tips for getting the most out of your  │")
    print("    │     budgeting journey                       │")
    print("    ├─────────────────────────────────────────────┤")
    print("    │                                             │")
    print("    │  💳 1. Set Up Your Budget                   │")
    print("    │  • Start by adding income sources           │")
    print("    │  • Create expense categories                │")
    print("    │  • Set realistic spending limits            │")
    print("    │                                             │")
    print("    │  📝 2. Track Your Expenses                  │")
    print("    │  • Record spending in Transactions          │")
    print("    │  • Add detailed notes                       │")
    print("    │  • Use filters to find transactions         │")
    print("    │                                             │")
    print("    │  💰 3. Build Your Savings                   │")
    print("    │  • Create savings goals                     │")
    print("    │  • Set target amounts                       │")
    print("    │  • Make regular contributions               │")
    print("    │                                             │")
    print("    │  📊 4. Review Your Progress                 │")
    print("    │  • Check Reports for insights               │")
    print("    │  • Compare actual vs budget                 │")
    print("    │  • Optimize your spending                   │")
    print("    │                                             │")
    print("    │         ┌─────────────────┐                 │")
    print("    │         │     Got It!     │                 │")
    print("    │         └─────────────────┘                 │")
    print("    │                                             │")
    print("    └─────────────────────────────────────────────┘")
    print()

def print_main_app_with_help():
    print("=" * 60)
    print("           MAIN APP WITH HELP BUTTON")
    print("=" * 60)
    print()
    print("    ┌─────────────────────────────────────────────┐")
    print("    │  Budget                            [?]      │")
    print("    ├─────────────────────────────────────────────┤")
    print("    │                                             │")
    print("    │  Income                     [+ Add]         │")
    print("    │  ┌─────────────────────────────────────────┐ │")
    print("    │  │ Salary             │ ₹3850.00   [×]   │ │")
    print("    │  └─────────────────────────────────────────┘ │")
    print("    │                                             │")
    print("    │  Budget Categories          [+ Add]         │")
    print("    │  ┌─────────────────────────────────────────┐ │")
    print("    │  │ 🏠 Rent            │ ₹1000.00  [✎][×] │ │")
    print("    │  └─────────────────────────────────────────┘ │")
    print("    │                                             │")
    print("    │  💰 Savings                                 │")
    print("    │  ┌─────────────────────────────────────────┐ │")
    print("    │  │ Emergency Fund     │ ₹200/month  [✎]  │ │")
    print("    │  └─────────────────────────────────────────┘ │")
    print("    │                                             │")
    print("    ├─────────────────────────────────────────────┤")
    print("    │  [💳] [📝] [💰] [🏦] [📊]                   │")
    print("    │ Budget Trans Savings Debt Report           │")
    print("    └─────────────────────────────────────────────┘")
    print()
    print("    Help button [?] provides easy access to tips!")
    print()

if __name__ == "__main__":
    print("RMinder First-Run Experience Visual Guide")
    print("=========================================")
    print()
    
    print_onboarding_screen()
    print("\n" + "▼" * 60)
    print("User taps 'Learn More' or '?' in main app")
    print("▼" * 60 + "\n")
    
    print_tips_screen()
    print("\n" + "▼" * 60)
    print("User taps 'Get Started' or 'Got It!'")  
    print("▼" * 60 + "\n")
    
    print_main_app_with_help()
    
    print("\nKey Benefits:")
    print("• Smooth first-run experience")
    print("• Comprehensive feature guidance")
    print("• Always-accessible help")
    print("• Privacy-first design")
    print("• Consistent with app theme")